package com.xyt.model;

import java.util.Date;

public class tbOrderInfo {

    private Long id;
    private String openid;
    private String clientnum;

    private String clientphone;


    private String qrcodeid;

    /**
     * .
     * This field corresponds to the database column tb_order_info.orderid
     *
     *
     */
    private String orderid;

    /**
     * .
     * This field corresponds to the database column tb_order_info.ordertype
     *
     *
     */
    private String ordertype;

    /**
     * .
     * This field corresponds to the database column tb_order_info.months
     *
     *
     */
    private Integer months;

    /**
     * .
     * This field corresponds to the database column tb_order_info.number
     *
     *
     */
    private String number;

    /**
     * .
     * This field corresponds to the database column tb_order_info.name
     *
     *
     */
    private String name;

    /**
     * .
     * This field corresponds to the database column tb_order_info.mobile
     *
     *
     */
    private String mobile;

    /**
     * .
     * This field corresponds to the database column tb_order_info.address
     *
     *
     */
    private String address;

    /**
     * .
     * This field corresponds to the database column tb_order_info.cost
     *
     *
     */
    private Integer cost;

    /**
     * .
     * This field corresponds to the database column tb_order_info.create_time
     *
     *
     */
    private Date createTime;

    /**
     * .
     * This field corresponds to the database column tb_order_info.update_time
     *
     *
     */
    private Date updateTime;

    /**
     * .
     * This field corresponds to the database column tb_order_info.status
     *
     *
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.id
     *
     * @return the value of tb_order_info.id
     *
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.id
     *
     * @param id the value for tb_order_info.id
     *
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.openid
     *
     * @return the value of tb_order_info.openid
     *
     *
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.openid
     *
     * @param openid the value for tb_order_info.openid
     *
     *
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.clientnum
     *
     * @return the value of tb_order_info.clientnum
     *
     *
     */
    public String getClientnum() {
        return clientnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.clientnum
     *
     * @param clientnum the value for tb_order_info.clientnum
     *
     *
     */
    public void setClientnum(String clientnum) {
        this.clientnum = clientnum == null ? null : clientnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.clientphone
     *
     * @return the value of tb_order_info.clientphone
     *
     *
     */
    public String getClientphone() {
        return clientphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.clientphone
     *
     * @param clientphone the value for tb_order_info.clientphone
     *
     *
     */
    public void setClientphone(String clientphone) {
        this.clientphone = clientphone == null ? null : clientphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.qrcodeid
     *
     * @return the value of tb_order_info.qrcodeid
     *
     *
     */
    public String getQrcodeid() {
        return qrcodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.qrcodeid
     *
     * @param qrcodeid the value for tb_order_info.qrcodeid
     *
     *
     */
    public void setQrcodeid(String qrcodeid) {
        this.qrcodeid = qrcodeid == null ? null : qrcodeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.orderid
     *
     * @return the value of tb_order_info.orderid
     *
     *
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.orderid
     *
     * @param orderid the value for tb_order_info.orderid
     *
     *
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.ordertype
     *
     * @return the value of tb_order_info.ordertype
     *
     *
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.ordertype
     *
     * @param ordertype the value for tb_order_info.ordertype
     *
     *
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.months
     *
     * @return the value of tb_order_info.months
     *
     *
     */
    public Integer getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.months
     *
     * @param months the value for tb_order_info.months
     *
     *
     */
    public void setMonths(Integer months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.number
     *
     * @return the value of tb_order_info.number
     *
     *
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.number
     *
     * @param number the value for tb_order_info.number
     *
     *
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.name
     *
     * @return the value of tb_order_info.name
     *
     *
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.name
     *
     * @param name the value for tb_order_info.name
     *
     *
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.mobile
     *
     * @return the value of tb_order_info.mobile
     *
     *
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.mobile
     *
     * @param mobile the value for tb_order_info.mobile
     *
     *
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.address
     *
     * @return the value of tb_order_info.address
     *
     *
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.address
     *
     * @param address the value for tb_order_info.address
     *
     *
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.cost
     *
     * @return the value of tb_order_info.cost
     *
     *
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.cost
     *
     * @param cost the value for tb_order_info.cost
     *
     *
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.create_time
     *
     * @return the value of tb_order_info.create_time
     *
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.create_time
     *
     * @param createTime the value for tb_order_info.create_time
     *
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.update_time
     *
     * @return the value of tb_order_info.update_time
     *
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.update_time
     *
     * @param updateTime the value for tb_order_info.update_time
     *
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.status
     *
     * @return the value of tb_order_info.status
     *
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.status
     *
     * @param status the value for tb_order_info.status
     *
     *
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}