package com.xyt.model;

import java.util.Date;

public class TbQrcodeStatistics {
    /**
     * .
     * This field corresponds to the database column tb_qrcode_statistics.date
     *
     *
     */
    private Date date;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_statistics.active_num
     *
     *
     */
    private Long activeNum;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_statistics.inactive_num
     *
     *
     */
    private Long inactiveNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_statistics.date
     *
     * @return the value of tb_qrcode_statistics.date
     *
     *
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_statistics.date
     *
     * @param date the value for tb_qrcode_statistics.date
     *
     *
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_statistics.active_num
     *
     * @return the value of tb_qrcode_statistics.active_num
     *
     *
     */
    public Long getActiveNum() {
        return activeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_statistics.active_num
     *
     * @param activeNum the value for tb_qrcode_statistics.active_num
     *
     *
     */
    public void setActiveNum(Long activeNum) {
        this.activeNum = activeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_statistics.inactive_num
     *
     * @return the value of tb_qrcode_statistics.inactive_num
     *
     *
     */
    public Long getInactiveNum() {
        return inactiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_statistics.inactive_num
     *
     * @param inactiveNum the value for tb_qrcode_statistics.inactive_num
     *
     *
     */
    public void setInactiveNum(Long inactiveNum) {
        this.inactiveNum = inactiveNum;
    }
}