package com.xyt.model;

import java.util.Date;

public class tbQrcodeInfo {
    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.id
     *
     *
     */
    private Long id;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.qrcode
     *
     *
     */
    private String qrcode;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.sid
     *
     *
     */
    private String sid;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.appid
     *
     *
     */
    private String appid;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.clientnum
     *
     *
     */
    private String clientnum;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.bindnum
     *
     *
     */
    private String bindnum;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.create_time
     *
     *
     */
    private Date createTime;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.begin_time
     *
     *
     */
    private Date beginTime;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.exp_time
     *
     *
     */
    private Date expTime;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.qrtype
     *
     *
     */
    private String qrtype;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.lifetime
     *
     *
     */
    private Integer lifetime;

    /**
     * .
     * This field corresponds to the database column tb_qrcode_info.status
     *
     *
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.id
     *
     * @return the value of tb_qrcode_info.id
     *
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.id
     *
     * @param id the value for tb_qrcode_info.id
     *
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.qrcode
     *
     * @return the value of tb_qrcode_info.qrcode
     *
     *
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.qrcode
     *
     * @param qrcode the value for tb_qrcode_info.qrcode
     *
     *
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.sid
     *
     * @return the value of tb_qrcode_info.sid
     *
     *
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.sid
     *
     * @param sid the value for tb_qrcode_info.sid
     *
     *
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.appid
     *
     * @return the value of tb_qrcode_info.appid
     *
     *
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.appid
     *
     * @param appid the value for tb_qrcode_info.appid
     *
     *
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.clientnum
     *
     * @return the value of tb_qrcode_info.clientnum
     *
     *
     */
    public String getClientnum() {
        return clientnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.clientnum
     *
     * @param clientnum the value for tb_qrcode_info.clientnum
     *
     *
     */
    public void setClientnum(String clientnum) {
        this.clientnum = clientnum == null ? null : clientnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.bindnum
     *
     * @return the value of tb_qrcode_info.bindnum
     *
     *
     */
    public String getBindnum() {
        return bindnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.bindnum
     *
     * @param bindnum the value for tb_qrcode_info.bindnum
     *
     *
     */
    public void setBindnum(String bindnum) {
        this.bindnum = bindnum == null ? null : bindnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.create_time
     *
     * @return the value of tb_qrcode_info.create_time
     *
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.create_time
     *
     * @param createTime the value for tb_qrcode_info.create_time
     *
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.begin_time
     *
     * @return the value of tb_qrcode_info.begin_time
     *
     *
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.begin_time
     *
     * @param beginTime the value for tb_qrcode_info.begin_time
     *
     *
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.exp_time
     *
     * @return the value of tb_qrcode_info.exp_time
     *
     *
     */
    public Date getExpTime() {
        return expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.exp_time
     *
     * @param expTime the value for tb_qrcode_info.exp_time
     *
     *
     */
    public void setExpTime(Date expTime) {
        this.expTime = expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.qrtype
     *
     * @return the value of tb_qrcode_info.qrtype
     *
     *
     */
    public String getQrtype() {
        return qrtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.qrtype
     *
     * @param qrtype the value for tb_qrcode_info.qrtype
     *
     *
     */
    public void setQrtype(String qrtype) {
        this.qrtype = qrtype == null ? null : qrtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.lifetime
     *
     * @return the value of tb_qrcode_info.lifetime
     *
     *
     */
    public Integer getLifetime() {
        return lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.lifetime
     *
     * @param lifetime the value for tb_qrcode_info.lifetime
     *
     *
     */
    public void setLifetime(Integer lifetime) {
        this.lifetime = lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_qrcode_info.status
     *
     * @return the value of tb_qrcode_info.status
     *
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_qrcode_info.status
     *
     * @param status the value for tb_qrcode_info.status
     *
     *
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}